{
 "title": "Node.js Dashboard",
 "description": "Monitor metrics for node.js and express router status.",
 "tags": [
  "node.js",
  "express",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "target", "query": "0.05,0.1,0.2,0.3,0.4,0.5" },
   { "name": "tolerated", "query": "0.1,0.2,0.3,0.4,0.5" },
   { "name": "restarts_interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "External Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(nodejs_external_memory_bytes{instance=\"localhost:3004\"}/1000000)"
    }
   ]
  },
  {
   "title": "Heap Size Total in MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes/(1000000)",
     "legendFormat": "Heap Size total "
    }
   ]
  },
  {
   "title": "Heap Size Used in MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes/(1000000)",
     "legendFormat": "Heap Size in MB"
    }
   ]
  },
  {
   "title": "Active Handles Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nodejs_active_handles_total" }
   ]
  },
  {
   "title": "Node Request Operation Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_requests_operations_total" }
   ]
  },
  {
   "title": "CPU Usage Efficiency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{instance=\"localhost:3004\", job=\"Nodejs- Application\"} *100 / process_cpu_seconds_total{instance=\"localhost:3004\", job=\"Nodejs- Application\"}"
    }
   ]
  },
  {
   "title": "Mean Event Loop Delay",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds"
    }
   ]
  },
  {
   "title": "Min Event Loop Delay",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_min_seconds"
    }
   ]
  },
  {
   "title": "Max Event Loop Delay",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_max_seconds"
    }
   ]
  },
  {
   "title": "Nodejs Version Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  { "title": "Node.js Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration SUM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration Minor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.001\",kind=\"minor\"}",
     "legendFormat": "Bucket: 001"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.01\",kind=\"minor\"}",
     "legendFormat": "Bucket: 0.01"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.1\",kind=\"minor\"}",
     "legendFormat": "Bucket: 0.1"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"1\",kind=\"minor\"}",
     "legendFormat": "Bucket: 1"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"2\",kind=\"minor\"}",
     "legendFormat": "Bucket: 2"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"5\",kind=\"minor\"}",
     "legendFormat": "Bucket: 5"
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"+Inf\",kind=\"minor\"}",
     "legendFormat": "Bucket: +Inf"
    }
   ]
  },
  {
   "title": "Nodejs Garbage Duration Major",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.001\",kind=\"major\"}",
     "legendFormat": "Bucket: \"0.001\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.01\",kind=\"major\"}",
     "legendFormat": "Bucket : \"0.01\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"0.1\",kind=\"major\"}",
     "legendFormat": "Bucket: \"0.1\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"1\",kind=\"major\"}",
     "legendFormat": "Bucket: \"1\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"2\",kind=\"major\"}",
     "legendFormat": "Bucket: \"2\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"5\",kind=\"major\"}",
     "legendFormat": "Bucket: \"5\""
    },
    {
     "expr": "nodejs_gc_duration_seconds_bucket{le=\"+Inf\",kind=\"major\"}",
     "legendFormat": "Bucket: \"+Inf\""
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=\"localhost:3004\"}",
     "legendFormat": "total"
    },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "used" },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  { "title": "Node.js Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Eventloop Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"localhost:3004\"}",
     "legendFormat": "last"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{instance=~\"$instance\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{instance=~\"$instance\"}",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{instance=\"localhost:3004\", job=\"Nodejs- Application\", type=\"Pipe\"}"
    },
    {
     "expr": "nodejs_active_handles{instance=\"localhost:3004\", job=\"Nodejs- Application\", type=\"Socket\"}"
    },
    {
     "expr": "nodejs_active_handles{instance=\"localhost:3004\", job=\"Nodejs- Application\", type=\"Server\"}"
    },
    {
     "expr": "nodejs_active_handles{instance=\"localhost:3004\", job=\"Nodejs- Application\", type=\"WriteStream\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=\"localhost:3004\", job=\"Nodejs- Application\"}[30s]) *100"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "virtual memory" },
    {
     "expr": "process_heap_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap memory"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_requests_status_422_operations_total",
     "legendFormat": "Error 422 status"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request"
    }
   ]
  }
 ]
}